# GitHub Actions workflow for automated Power BI visual builds
name: Build and Release

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git history-based versioning
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Generate CI version
      run: npm run version:ci
      env:
        BUILD_NUMBER: ${{ github.run_number }}
    
    - name: Build Power BI visual
      run: npm run build:ci
    
    - name: Upload visual package
      uses: actions/upload-artifact@v4
      with:
        name: powerbi-visual-${{ github.run_number }}
        path: dist/*.pbiviz
        retention-days: 30

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate release version
      run: npm run version:ci
      env:
        BUILD_NUMBER: ${{ github.run_number }}
    
    - name: Build for release
      run: npm run build:ci
    
    - name: Get version from package.json
      id: get_version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Get .pbiviz filename
      id: get_filename
      run: |
        PBIVIZ_FILE=$(ls dist/*.pbiviz | head -1)
        FILENAME=$(basename "$PBIVIZ_FILE")
        echo "filename=$FILENAME" >> $GITHUB_OUTPUT
        echo "filepath=$PBIVIZ_FILE" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: maplumi-pbi v${{ steps.get_version.outputs.version }}
        body: |
          🎨 **Maplumi Power BI Visual Release**
          
          **Version:** ${{ steps.get_version.outputs.version }}
          **Build:** ${{ github.run_number }}
          **Commit:** ${{ github.sha }}
          
          ### 📦 Package Details
          - **Visual Name:** Maplumi Power BI Visual
          - **File:** ${{ steps.get_filename.outputs.filename }}
          - **Type:** Power BI Custom Visual (.pbiviz)
          
          ### 🚀 Installation
          1. Download the `.pbiviz` file below
          2. Import into Power BI Desktop
          3. Add to your reports and dashboards
          
          ### 📋 What's New
          See commit history for detailed changes.
        files: |
          ${{ steps.get_filename.outputs.filepath }}
        draft: false
        prerelease: false
